// ── Config ──

// Priority:
//   1) VITE_API_URL env var (build-time)
//   2) Electron userData config (via initApiConfig)
//   3) localStorage fallback (browser dev)
//   4) http://localhost:3001
//
// Set production URL at build time:
//   VITE_API_URL=http://your-server:3001 npm run build

let _apiBase = 'http://5.164.42.189:3001'

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

function resolveApiBase(): string {
  if (import.meta.env.VITE_API_URL) return (import.meta.env.VITE_API_URL as string).replace(/\/$/, '')
  try {
    const stored = localStorage.getItem('predator_api_url')
    if (stored) return stored.replace(/\/$/, '')
  } catch { /* localStorage unavailable */ }
  return _apiBase
}

export function getApiBase(): string {
  return _apiBase
}

export function setApiBase(url: string): void {
  _apiBase = url.replace(/\/$/, '')
}

/** Load API URL from Electron config or env. Call once on app start. */
export async function initApiConfig(): Promise<string> {
  const api = window.electronAPI
  if (api?.getApiBase) {
    try {
      const url = await api.getApiBase()
      if (url) {
        setApiBase(url)
        return url
      }
    } catch { /* fallback below */ }
  }
  const resolved = resolveApiBase()
  setApiBase(resolved)
  return resolved
}

// ── Types ──

export interface TokenValidateResponse {
  valid: boolean
  token_id?: number
  error?: string
}

export interface TokenUseResponse {
  valid: boolean
  token_id?: number
  message?: string
  error?: string
}

export interface RequestAccessResponse {
  success: boolean
  request_id?: number
  message?: string
  error?: string
}

export interface RequestStatusResponse {
  id: number
  pc_username: string
  status: 'pending' | 'approved' | 'rejected'
  created_at: string
  error?: string
}

// ── Helpers ──

async function fetchApi<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(`${getApiBase()}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })

  // Parse JSON safely — server may return empty body on network errors
  let data: unknown
  try { data = await res.json() } catch { /* empty/invalid JSON — handled below */ }

  if (!res.ok) {
    if (data === undefined) {
      throw new Error(`Сервер недоступен (HTTP ${res.status}). Проверьте подключение.`)
    }
    // Legacy: token validation returns { valid: boolean } on non-OK status
    if (isRecord(data) && typeof data.valid === 'boolean') return data as T
    const errorMessage = isRecord(data) && typeof data.error === 'string' ? data.error : `HTTP ${res.status}`
    throw new Error(errorMessage)
  }
  if (data === undefined) {
    throw new Error('Сервер вернул пустой ответ. Попробуйте позже.')
  }
  return data as T
}

async function fetchGet<T>(path: string): Promise<T> {
  const res = await fetch(`${getApiBase()}${path}`)

  let data: unknown
  try { data = await res.json() } catch { /* empty/invalid JSON — handled below */ }

  if (!res.ok) {
    throw new Error(`Сервер недоступен (HTTP ${res.status}). Проверьте подключение.`)
  }
  if (data === undefined) {
    throw new Error('Сервер вернул пустой ответ. Попробуйте позже.')
  }
  return data as T
}

// ── Auth API ──

export async function validateToken(token: string): Promise<TokenValidateResponse> {
  return fetchApi<TokenValidateResponse>('/api/auth/token', { token })
}

export async function useToken(token: string, pc_username: string): Promise<TokenUseResponse> {
  return fetchApi<TokenUseResponse>('/api/auth/token/use', { token, pc_username })
}

export async function requestAccess(pc_username: string): Promise<RequestAccessResponse> {
  return fetchApi<RequestAccessResponse>('/api/auth/request', { pc_username })
}

export async function checkRequestStatus(id: number): Promise<RequestStatusResponse> {
  return fetchGet<RequestStatusResponse>(`/api/auth/status/${id}`)
}

// ── Scan Submission API ──

export interface EvidenceRecord {
  id: string
  source: string
  category: string
  weight: number
  confidence: number
  explanation: string
  raw: string
  timestamp: string
  relatedFindingIds?: string[]
}

/** Finding with rich metadata for server-side analysis */
export interface SubmitScanFinding {
  path: string
  fileName: string
  type: string
  risk: 'critical' | 'high' | 'medium' | 'low'
  matches: string[]
  /** Full SHA256 hash (if available) */
  sha256?: string
  /** First 64KB SHA256 — used for safe-files matching */
  partialHash?: string
  /** File size in bytes */
  size?: number
  /** Last modification timestamp */
  modifiedAt?: string
  /** Pre-classified finding kind (dma/process/cleaner/registry/browser/file) */
  findingKind?: string
  /** Structured evidence generated by the client scorer. */
  evidence?: EvidenceRecord[]
  findingId?: string
  riskScore?: number
  riskExplanation?: string
}

export interface SubmitScanRequest {
  token_id?: number
  pc_username: string
  mode: string
  total_scanned: number
  suspicious_files: number
  high_risk_count: number
  scan_time_ms: number
  results: SubmitScanFinding[]
  /** Client version for server-side compatibility tracking */
  client_version?: string
}

export interface SubmitScanResponse {
  success: boolean
  message: string
  /** Server-side classification summary (if processed) */
  auto_safe_count?: number
  auto_malicious_count?: number
  pending_count?: number
}

// ── Retry helper ──

interface QueueItem {
  id: string
  url: string
  body: unknown
  retries: number
  maxRetries: number
  createdAt: string
}

const QUEUE_KEY = 'predator_offline_queue'
const MAX_RETRIES = 3

function loadQueue(): QueueItem[] {
  try {
    const raw = localStorage.getItem(QUEUE_KEY)
    return raw ? JSON.parse(raw) : []
  } catch { return [] }
}

function saveQueue(queue: QueueItem[]): void {
  try {
    localStorage.setItem(QUEUE_KEY, JSON.stringify(queue.slice(-100)))
  } catch {}
}

function addToQueue(url: string, body: unknown): void {
  const queue = loadQueue()
  queue.push({
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    url,
    body,
    retries: 0,
    maxRetries: MAX_RETRIES,
    createdAt: new Date().toISOString(),
  })
  saveQueue(queue)
  // Attempt to process queue immediately
  processQueue().catch(() => {})
}

/** Process pending offline queue items */
async function processQueue(): Promise<void> {
  const queue = loadQueue()
  if (queue.length === 0) return

  const remaining: QueueItem[] = []
  for (const item of queue) {
    try {
      const res = await fetch(`${getApiBase()}${item.url}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(item.body),
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
    } catch {
      item.retries++
      if (item.retries < item.maxRetries) {
        remaining.push(item)
      }
      // else: discard after max retries
    }
  }
  saveQueue(remaining)
}

// Retry wrapper: 3 attempts with exponential backoff
async function fetchApiWithRetry<T>(
  path: string,
  body: unknown,
  retries = MAX_RETRIES,
): Promise<T> {
  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      return await fetchApi<T>(path, body)
    } catch (err) {
      if (attempt < retries) {
        // Exponential backoff: 1s, 2s, 4s
        const delay = 1000 * Math.pow(2, attempt - 1)
        await new Promise(r => setTimeout(r, delay))
      } else {
        // Last attempt failed — add to offline queue
        addToQueue(path, body)
        throw err
      }
    }
  }
  throw new Error('All retries exhausted')
}

// ── Online status tracking for queue processing ──

let _onlineListenerSet = false

function ensureOnlineListener(): void {
  if (_onlineListenerSet) return
  _onlineListenerSet = true
  window.addEventListener('online', () => {
    processQueue().catch(() => {})
  })
}

export async function submitScan(data: SubmitScanRequest): Promise<SubmitScanResponse> {
  ensureOnlineListener()
  return fetchApiWithRetry<SubmitScanResponse>('/api/auth/submit-scan', data)
}

// ── Cloud Hash Submission API ──

export interface SuspectHash {
  sha256: string
  file_name?: string
  file_size?: number
  risk_score?: number
}

export interface SubmitHashesResponse {
  success: boolean
  inserted: number
  total: number
}

export async function submitHashes(hashes: SuspectHash[], pc_username?: string, token_id?: number): Promise<SubmitHashesResponse> {
  return fetchApi<SubmitHashesResponse>('/api/auth/submit-hashes', {
    hashes,
    pc_username,
    token_id,
  })
}

export interface CloudHash {
  sha256: string
  file_name: string
  file_size: number
  added_at: string
}

export interface FetchHashesResponse {
  count: number
  hashes: CloudHash[]
}

export async function fetchCheatHashes(after?: string): Promise<FetchHashesResponse> {
  const q = after ? `?after=${after}` : ''
  return fetchGet<FetchHashesResponse>(`/api/auth/fetch-hashes${q}`)
}
